<template>
  <section class="shop-list-view"><header><p>{{ categoryName || '探索门店' }}</p><h1>{{ categoryName ? `${categoryName}好去处` : '附近好店' }}</h1><div v-if="types.length" class="type-list" aria-label="门店分类"><button v-for="type in types" :key="type.id" :data-test="`shop-type-${type.id}`" type="button" :class="{ active: type.id === typeId }" @click="selectType(type)">{{ type.name || '未命名分类' }}</button></div><div class="sort-list" role="group" aria-label="门店排序"><button v-for="item in sortOptions" :key="item.value" type="button" :aria-pressed="sortBy === item.value" :class="{ active: sortBy === item.value }" @click="changeSort(item.value)">{{ item.label }}</button></div></header><section class="shop-list" aria-live="polite"><PageState v-if="state !== 'ready' && !shops.length" :state="state" :message="errorMessage" @retry="reload"/><template v-else><ShopCard v-for="shop in shops" :key="shop.id" :shop="shop" @open="openShop"/><PageState v-if="pageError" state="error" :message="pageError" @retry="() => loadNext()"/><button v-else-if="!exhausted" type="button" class="load-more" :disabled="loading" @click="() => loadNext()">{{ loading ? '正在加载…' : '加载更多门店' }}</button><p v-else class="end">已经到底啦</p></template></section></section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getShopTypes, getShopsByType, searchShops } from '@/api/shop'
import PageState from '@/components/common/PageState.vue'
import ShopCard from '@/components/content/ShopCard.vue'
import type { Shop, ShopType } from '@/types/api'
type ViewState = 'loading' | 'error' | 'empty' | 'ready'
const route = useRoute(); const router = useRouter(); const shops = ref<Shop[]>([]); const types = ref<ShopType[]>([]); const state = ref<ViewState>('loading'); const errorMessage = ref(''); const pageError = ref(''); const page = ref(1); const loading = ref(false); const exhausted = ref(false); let queryEpoch = 0
const sortOptions = [{ value: '', label: '距离' }, { value: 'comments', label: '人气' }, { value: 'score', label: '评分' }]
const typeId = computed(() => Number(route.query.type)); const keyword = computed(() => typeof route.query.name === 'string' ? route.query.name : ''); const sortBy = computed(() => typeof route.query.sort === 'string' && sortOptions.some((item) => item.value === route.query.sort) ? route.query.sort : ''); const shouldSearch = computed(() => !Number.isFinite(typeId.value) && !!keyword.value); const categoryName = computed(() => types.value.find((type) => type.id === typeId.value)?.name || keyword.value)
async function loadTypes() { try { types.value = await getShopTypes() } catch { /* 分类失败不阻断门店查询 */ } }
async function loadNext(reset = false) { if ((!reset && loading.value) || (!reset && exhausted.value)) return; if (reset) { queryEpoch += 1; shops.value = []; page.value = 1; exhausted.value = false; loading.value = false; pageError.value = ''; errorMessage.value = ''; state.value = 'loading' } if (!Number.isFinite(typeId.value) && !keyword.value) { state.value = 'empty'; return } const requestEpoch = queryEpoch; const current = page.value; loading.value = true; pageError.value = ''; try { const params = { typeId: typeId.value, current, sortBy: sortBy.value || undefined, ...(sortBy.value === '' ? { x: 120.149993, y: 30.334229 } : {}) }; const next = shouldSearch.value ? await searchShops(keyword.value, current) : await getShopsByType(params); if (requestEpoch !== queryEpoch) return; const existing = new Set(shops.value.map((shop) => shop.id)); shops.value.push(...next.filter((shop) => !existing.has(shop.id))); page.value = current + 1; exhausted.value = next.length === 0; state.value = shops.value.length ? 'ready' : 'empty' } catch { if (requestEpoch !== queryEpoch) return; errorMessage.value = '门店加载失败，请稍后重试。'; if (shops.value.length) { pageError.value = errorMessage.value; state.value = 'ready' } else state.value = 'error' } finally { if (requestEpoch === queryEpoch) loading.value = false } }
function reload() { return loadNext(true) } function changeSort(value: string) { if (sortBy.value === value) return; void router.push({ name: 'shops', query: { ...route.query, sort: value } }) } function selectType(type: ShopType) { if (type.id === undefined) return; void router.push({ name: 'shops', query: { type: type.id, name: type.name || '', sort: sortBy.value } }) } function openShop(shop: Shop) { if (shop.id !== undefined) void router.push({ name: 'shop-detail', params: { id: shop.id } }) }
watch(() => [route.query.type, route.query.name, route.query.sort], () => { void loadNext(true) })
onMounted(() => { void loadTypes(); void loadNext(true) })
</script>

<style scoped>
.shop-list-view{max-width:900px;margin:0 auto}.shop-list-view header{padding:14px 0 22px}.shop-list-view header p{margin:0;color:var(--color-primary);font-size:.88rem;font-weight:700}.shop-list-view h1{margin:6px 0 18px;font-size:clamp(1.8rem,4vw,2.6rem)}.type-list,.sort-list{display:flex;gap:8px;overflow:auto}.type-list{margin-bottom:10px}.type-list button,.sort-list button{min-width:52px;min-height:44px;padding:8px 14px;border:1px solid var(--color-border);border-radius:999px;background:var(--color-surface);color:var(--color-muted);font:inherit;cursor:pointer}.type-list button.active,.sort-list button.active{border-color:var(--color-primary);background:#fff0ea;color:var(--color-primary);font-weight:700}.shop-list{display:grid;gap:14px}.load-more{min-height:44px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-primary);font:inherit;font-weight:700;cursor:pointer}.load-more:disabled{cursor:wait}.end{margin:6px 0;color:var(--color-muted);font-size:.85rem;text-align:center}
</style>
