<template>
  <section class="publish-blog"><header><div><p>分享此刻</p><h1>发布探店记录</h1></div><button type="button" :disabled="submitting" @click="submit">{{ submitting ? '发布中…' : '发布' }}</button></header><form @submit.prevent="submit"><label>标题<input v-model.trim="title" maxlength="80" placeholder="给这次探店起个标题"></label><label>内容<textarea v-model.trim="content" rows="7" maxlength="2000" placeholder="记录你的发现和体验，换行会被保留。"></textarea></label><ImageUploader v-model="images"/><section class="shop-picker" aria-labelledby="shop-picker-title"><div><h2 id="shop-picker-title">关联门店</h2><p>{{ selectedShop?.name || '请选择本次探访的门店' }}</p></div><button type="button" @click="showShopPicker = !showShopPicker">{{ showShopPicker ? '收起' : '选择门店' }}</button><div v-if="showShopPicker" class="shop-picker__panel"><label>搜索门店<input v-model.trim="shopKeyword" placeholder="输入门店名称" @keyup.enter.prevent="findShops"></label><button type="button" :disabled="searching" @click="findShops">{{ searching ? '搜索中…' : '搜索' }}</button><p v-if="shopError" class="form-error" role="alert">{{ shopError }}</p><button v-for="shop in shops" :key="shop.id" type="button" class="shop-result" @click="selectShop(shop)"><strong>{{ shop.name || '未命名门店' }}</strong><span>{{ shop.area || shop.address || '' }}</span></button></div></section><p v-if="formError" class="form-error" role="alert">{{ formError }}</p></form></section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import { publishBlog } from '@/api/blog'
import { searchShops } from '@/api/shop'
import ImageUploader from '@/components/content/ImageUploader.vue'
import type { Shop } from '@/types/api'
const router = useRouter(); const title = ref(''); const content = ref(''); const images = ref<string[]>([]); const selectedShop = ref<Shop>(); const showShopPicker = ref(false); const shopKeyword = ref(''); const shops = ref<Shop[]>([]); const searching = ref(false); const submitting = ref(false); const formError = ref(''); const shopError = ref('')
async function findShops() { searching.value = true; shopError.value = ''; try { shops.value = await searchShops(shopKeyword.value) } catch { shopError.value = '门店搜索失败，请稍后重试。' } finally { searching.value = false } }
function selectShop(shop: Shop) { selectedShop.value = shop; showShopPicker.value = false }
async function submit() { if (submitting.value) return; if (selectedShop.value?.id === undefined || !title.value || !content.value || !images.value.length) { formError.value = '请选择门店，并填写标题、内容和至少一张图片。'; return } submitting.value = true; formError.value = ''; try { await publishBlog({ shopId: selectedShop.value.id, title: title.value, content: content.value, images: images.value.join(',') }); ElMessage.success('发布成功'); await router.push({ name: 'me' }) } catch { formError.value = '发布失败，请稍后重试。' } finally { submitting.value = false } }
</script>

<style scoped>
.publish-blog{max-width:760px;margin:0 auto}.publish-blog header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px}.publish-blog header p{margin:0;color:var(--color-primary);font-size:.85rem;font-weight:700}.publish-blog h1{margin:4px 0 0;font-size:clamp(1.7rem,4vw,2.4rem)}.publish-blog header>button,.shop-picker>button,.shop-picker__panel>button{min-height:44px;padding:8px 15px;border:0;border-radius:var(--radius-control);background:var(--color-primary);color:#fff;font:inherit;font-weight:700;cursor:pointer}.publish-blog header>button:disabled,.shop-picker__panel>button:disabled{cursor:wait;opacity:.6}.publish-blog form{display:grid;gap:20px;padding:18px;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface);box-shadow:var(--shadow-card)}.publish-blog label{display:grid;gap:7px;font-weight:700}.publish-blog input,.publish-blog textarea{width:100%;padding:11px 12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:#fff;color:var(--color-ink);font:inherit;font-weight:400}.publish-blog textarea{resize:vertical}.shop-picker{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding-top:16px;border-top:1px solid var(--color-border)}.shop-picker h2,.shop-picker p{margin:0}.shop-picker h2{font-size:1rem}.shop-picker p{color:var(--color-muted);font-size:.84rem}.shop-picker__panel{grid-column:1/-1;display:grid;gap:9px;padding:12px;border-radius:var(--radius-control);background:#fff5ee}.shop-result{display:grid;gap:2px;padding:10px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:#fff;color:inherit;font:inherit;text-align:left;cursor:pointer}.shop-result span{color:var(--color-muted);font-size:.8rem}.form-error{margin:0;color:var(--color-error);font-size:.88rem}
</style>
