<template>
  <section class="image-uploader" aria-labelledby="image-uploader-title"><div class="image-uploader__head"><h2 id="image-uploader-title">上传图片</h2><span>{{ modelValue.length }}/{{ max }}</span></div><div class="image-uploader__grid"><figure v-for="(url, index) in modelValue" :key="url" class="image-uploader__preview"><img :src="url" :alt="`已上传图片 ${index + 1}`" width="160" height="160" loading="lazy"><button type="button" style="width:44px;height:44px" :data-test="`remove-image-${index}`" :disabled="removingIndex === index" :aria-label="`删除图片 ${index + 1}`" @click="remove(index)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18" fill="none" stroke="currentColor" stroke-width="2"/></svg></button></figure><button v-if="modelValue.length < max" type="button" class="image-uploader__add" :disabled="uploading" @click="input?.click()"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14" fill="none" stroke="currentColor" stroke-width="2"/></svg><span>{{ uploading ? '上传中…' : '添加图片' }}</span></button></div><label class="sr-only" for="blog-image-input">选择博客图片</label><input id="blog-image-input" ref="input" type="file" accept="image/*" class="sr-only" @change="selectFile"><p class="image-uploader__status" aria-live="polite">{{ status }}</p></section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { deleteBlogImage, normalizeBlogImageUrl, uploadBlogImage } from '@/api/upload'
const props = withDefaults(defineProps<{ modelValue: string[]; max?: number }>(), { max: 9 })
const emit = defineEmits<{ 'update:modelValue': [value: string[]] }>()
const input = ref<HTMLInputElement>(); const uploading = ref(false); const removingIndex = ref<number>(); const status = ref('')
async function selectFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file || uploading.value || props.modelValue.length >= props.max) return; uploading.value = true; status.value = '图片上传中…'; try { const path = await uploadBlogImage(file); emit('update:modelValue', [...props.modelValue, normalizeBlogImageUrl(path)]); status.value = '图片上传成功'; } catch { status.value = '图片上传失败，请重试'; } finally { uploading.value = false; if (input.value) input.value.value = '' } }
async function remove(index: number) { const path = props.modelValue[index]; if (!path || removingIndex.value !== undefined) return; removingIndex.value = index; status.value = '正在删除图片…'; try { await deleteBlogImage(path); emit('update:modelValue', props.modelValue.filter((_, itemIndex) => itemIndex !== index)); status.value = '图片已删除'; } catch { status.value = '图片删除失败，请重试'; } finally { removingIndex.value = undefined } }
</script>

<style scoped>
.image-uploader{display:grid;gap:10px}.image-uploader__head{display:flex;align-items:baseline;justify-content:space-between}.image-uploader__head h2{margin:0;font-size:1rem}.image-uploader__head span,.image-uploader__status{margin:0;color:var(--color-muted);font-size:.82rem}.image-uploader__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.image-uploader__preview,.image-uploader__add{position:relative;aspect-ratio:1;margin:0;overflow:hidden;border:1px solid var(--color-border);border-radius:var(--radius-control);background:#fff5ee}.image-uploader__preview img{width:100%;height:100%;object-fit:cover}.image-uploader__preview button{position:absolute;top:5px;right:5px;display:grid;place-items:center;padding:0;border:0;border-radius:50%;background:rgba(44,35,32,.75);color:#fff;cursor:pointer}.image-uploader__preview button:disabled{cursor:wait;opacity:.6}.image-uploader__preview svg,.image-uploader__add svg{width:20px}.image-uploader__add{display:grid;place-items:center;gap:4px;min-height:44px;color:var(--color-primary);font:inherit;font-size:.8rem;cursor:pointer}.image-uploader__add:disabled{cursor:wait;color:var(--color-muted)}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
</style>
