<template>
  <section class="auth-view" aria-labelledby="login-title"><RouterLink class="auth-view__brand" :to="{ name: 'home' }"><BrandMark />探店星球</RouterLink><div class="auth-panel"><p class="auth-panel__kicker">欢迎来到城市的每个角落</p><h1 id="login-title">验证码登录</h1><p v-if="route.query.registered === '1'" class="success-message" role="status">注册成功，请登录</p><form novalidate :aria-describedby="submitError ? 'login-submit-error' : undefined" @submit.prevent="submit"><label for="phone">手机号</label><input id="phone" v-model.trim="form.phone" data-test="phone" type="tel" inputmode="numeric" autocomplete="tel" placeholder="请输入手机号" :aria-invalid="!!errors.phone" :aria-describedby="errors.phone ? 'phone-error' : undefined" @input="errors.phone = ''"><p v-if="errors.phone" id="phone-error" class="field-error">{{ errors.phone }}</p><div class="code-field"><div><label for="code">验证码</label><input id="code" v-model.trim="form.code" data-test="code" inputmode="numeric" autocomplete="one-time-code" placeholder="6 位数字" maxlength="6" :aria-invalid="!!errors.code" :aria-describedby="errors.code ? 'code-error' : undefined" @input="errors.code = ''"></div><button type="button" data-test="send-code" :disabled="cooldown > 0 || sending" @click="requestCode">{{ cooldown ? `${cooldown} 秒后重试` : '获取验证码' }}</button></div><p v-if="errors.code" id="code-error" class="field-error">{{ errors.code }}</p><label class="agreement" style="min-height:44px"><input v-model="form.agreed" data-test="agreement" type="checkbox" :aria-invalid="!!errors.agreed" :aria-describedby="errors.agreed ? 'agreement-error' : undefined">我已阅读并同意<a href="#agreement">用户协议</a></label><p v-if="errors.agreed" id="agreement-error" class="field-error">{{ errors.agreed }}</p><p v-if="submitError" id="login-submit-error" class="field-error" role="alert">{{ submitError }}</p><button class="auth-submit" type="submit" :disabled="submitting">{{ submitting ? '登录中…' : '登录' }}</button></form><div class="auth-links"><RouterLink class="password-link" :to="{ name: 'password-login', query: route.query }">使用密码登录</RouterLink><RouterLink class="password-link" :to="{ name: 'register' }">没有账号？立即注册</RouterLink></div></div></section>
</template>

<script setup lang="ts">
import { onBeforeUnmount, reactive, ref } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import BrandMark from '@/components/common/BrandMark.vue'
import { sendCode } from '@/api/user'
import { useAuthStore } from '@/stores/auth'
const phonePattern = /^1[3-9]\d{9}$/
const codePattern = /^\d{6}$/
const route = useRoute(); const router = useRouter(); const auth = useAuthStore()
const form = reactive({ phone: typeof route.query.phone === 'string' ? route.query.phone : '', code: '', agreed: false }); const errors = reactive({ phone: '', code: '', agreed: '' }); const submitError = ref(''); const cooldown = ref(0); const sending = ref(false); const submitting = ref(false); let timer: ReturnType<typeof setInterval> | undefined
function validatePhone() { errors.phone = phonePattern.test(form.phone) ? '' : '请输入有效的中国大陆手机号'; return !errors.phone }
function validateForm() { const phoneValid = validatePhone(); errors.code = codePattern.test(form.code) ? '' : '请输入 6 位数字验证码'; errors.agreed = form.agreed ? '' : '请先同意用户协议'; return phoneValid && !errors.code && !errors.agreed }
function startCooldown() { cooldown.value = 60; timer = setInterval(() => { cooldown.value -= 1; if (cooldown.value <= 0 && timer) { clearInterval(timer); timer = undefined } }, 1000) }
async function requestCode() { if (!validatePhone() || cooldown.value) return; sending.value = true; errors.code = ''; try { await sendCode(form.phone); startCooldown() } catch (error) { errors.code = error instanceof Error && error.message.trim() ? error.message : '验证码发送失败，请稍后重试' } finally { sending.value = false } }
async function submit() { submitError.value = ''; if (!validateForm()) return; submitting.value = true; try { await auth.signIn({ phone: form.phone, loginType: 'code', verifyCode: form.code }); await router.push(typeof route.query.redirect === 'string' ? route.query.redirect : '/') } catch { submitError.value = '登录失败，请核对信息后重试' } finally { submitting.value = false } }
onBeforeUnmount(() => { if (timer) clearInterval(timer) })
</script>

<style scoped>
.auth-view{max-width:460px;margin:clamp(20px,8vw,88px) auto;padding:0 16px}.auth-view__brand{display:inline-flex;align-items:center;gap:8px;color:var(--color-primary);font-size:1.12rem;font-weight:800}.auth-panel{margin-top:28px;padding:clamp(22px,5vw,38px);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-card);box-shadow:0 16px 34px rgba(91,48,26,.08)}.auth-panel__kicker{margin:0;color:var(--color-muted);font-size:.9rem}.auth-panel h1{margin:8px 0 28px;font-size:1.85rem}.auth-panel form{display:grid;gap:8px}.auth-panel label{font-weight:700}.auth-panel input{width:100%;min-height:46px;padding:10px 12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:#fff;font:inherit}.code-field{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end}.code-field>div{display:grid;gap:8px}.code-field button,.auth-submit{min-height:46px;padding:10px 14px;border:0;border-radius:var(--radius-control);background:#fff0ea;color:var(--color-primary);font:inherit;font-weight:700;cursor:pointer}.auth-submit{margin-top:10px;background:var(--color-primary);color:#fff}.auth-submit:disabled,.code-field button:disabled{opacity:.6;cursor:not-allowed}.agreement{display:flex;align-items:center;gap:7px;min-height:44px;margin-top:12px;font-size:.86rem;font-weight:400!important}.agreement input{width:18px;min-height:18px}.agreement a{color:var(--color-primary);text-decoration:underline}.field-error{margin:0;color:#b42318;font-size:.84rem}.success-message{margin:-14px 0 18px;padding:10px 12px;border-radius:var(--radius-control);background:#edf8f0;color:#26713a;font-size:.9rem}.auth-links{display:flex;flex-wrap:wrap;justify-content:space-between;gap:4px 16px;margin-top:14px}.password-link{display:inline-flex;min-height:44px;align-items:center;color:var(--color-primary);font-weight:700}
</style>
