<template>
  <section class="auth-view" aria-labelledby="password-login-title"><RouterLink class="auth-view__brand" :to="{ name: 'home' }"><BrandMark />探店星球</RouterLink><div class="auth-panel"><p class="auth-panel__kicker">欢迎回来</p><h1 id="password-login-title">密码登录</h1><form novalidate :aria-describedby="submitError ? 'password-login-submit-error' : undefined" @submit.prevent="submit"><label for="phone">手机号</label><input id="phone" v-model.trim="form.phone" type="tel" inputmode="numeric" autocomplete="tel" placeholder="请输入手机号" :aria-invalid="!!errors.phone" :aria-describedby="errors.phone ? 'password-phone-error' : undefined" @input="errors.phone = ''"><p v-if="errors.phone" id="password-phone-error" class="field-error">{{ errors.phone }}</p><label for="password">密码</label><input id="password" v-model="form.password" type="password" autocomplete="current-password" placeholder="请输入密码" :aria-invalid="!!errors.password" :aria-describedby="errors.password ? 'password-error' : undefined" @input="errors.password = ''"><p v-if="errors.password" id="password-error" class="field-error">{{ errors.password }}</p><p v-if="submitError" id="password-login-submit-error" class="field-error" role="alert">{{ submitError }}</p><button class="auth-submit" type="submit" :disabled="submitting">{{ submitting ? '登录中…' : '登录' }}</button></form><RouterLink class="password-link" :to="{ name: 'login', query: route.query }">使用验证码登录</RouterLink></div></section>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import BrandMark from '@/components/common/BrandMark.vue'
import { useAuthStore } from '@/stores/auth'
const phonePattern = /^1([38][0-9]|4[579]|5[0-35-9]|6[6]|7[0135678]|9[89])\d{8}$/
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const form = reactive({ phone: '', password: '' }); const errors = reactive({ phone: '', password: '' }); const submitError = ref(''); const submitting = ref(false)
async function submit() { errors.phone = phonePattern.test(form.phone) ? '' : '请输入有效的中国大陆手机号'; errors.password = form.password ? '' : '请输入密码'; submitError.value = ''; if (errors.phone || errors.password) return; submitting.value = true; try { await auth.signIn({ phone: form.phone, password: form.password }); await router.push(typeof route.query.redirect === 'string' ? route.query.redirect : '/me') } catch { submitError.value = '登录失败，请核对信息后重试' } finally { submitting.value = false } }
</script>

<style scoped>
.auth-view{max-width:460px;margin:clamp(20px,8vw,88px) auto;padding:0 16px}.auth-view__brand{display:inline-flex;align-items:center;gap:8px;color:var(--color-primary);font-size:1.12rem;font-weight:800}.auth-panel{margin-top:28px;padding:clamp(22px,5vw,38px);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-card);box-shadow:0 16px 34px rgba(91,48,26,.08)}.auth-panel__kicker{margin:0;color:var(--color-muted);font-size:.9rem}.auth-panel h1{margin:8px 0 28px;font-size:1.85rem}.auth-panel form{display:grid;gap:8px}.auth-panel label{font-weight:700}.auth-panel input{width:100%;min-height:46px;padding:10px 12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:#fff;font:inherit}.auth-submit{min-height:46px;margin-top:10px;padding:10px 14px;border:0;border-radius:var(--radius-control);background:var(--color-primary);color:#fff;font:inherit;font-weight:700;cursor:pointer}.auth-submit:disabled{opacity:.6;cursor:not-allowed}.field-error{margin:0;color:#b42318;font-size:.84rem}.password-link{display:inline-flex;min-height:44px;align-items:center;margin-top:18px;color:var(--color-primary);font-weight:700}
</style>
