<template>
  <section class="home-view"><div class="home-hero"><p>杭州 · 城市慢游指南</p><h1>今天，去哪里逛逛？</h1><button type="button" class="search-entry" aria-label="搜索入口暂未开放" disabled><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m20 20-4.3-4.3m2.3-5.2a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z" fill="none" stroke="currentColor" stroke-width="2"/></svg>搜店铺、地点和灵感（暂未开放）</button></div><section class="type-section" aria-labelledby="type-title"><h2 id="type-title">发现附近</h2><PageState v-if="typeState !== 'ready'" :state="typeState" :message="typeError" @retry="loadTypes"/><div v-else class="type-list"><button v-for="type in types" :key="type.id" type="button" class="type-item" @click="goType(type)"><img v-if="type.icon" :src="type.icon" alt=""><span v-else class="type-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 7h14v12H5zM8 4h8v3H8z" fill="currentColor"/></svg></span><span>{{ type.name || '分类' }}</span></button></div></section><section class="hot-section" aria-labelledby="hot-title"><div class="section-heading"><h2 id="hot-title">热门博客</h2><span>此刻正在发生</span></div><PageState v-if="!blogs.length && blogState !== 'ready'" :state="blogState" :message="blogError" @retry="reloadBlogs"/><div v-else class="blog-grid"><BlogCard v-for="blog in blogs" :key="blog.id" :blog="blog" @open="goBlog" @like="handleLike"/></div><PageState v-if="paginationError" state="error" :message="paginationError" @retry="retryPage"/><div ref="loadMoreTrigger" class="load-more" aria-live="polite">{{ loadingMore ? '正在加载更多…' : exhausted ? '已经到底啦' : '' }}</div></section></section>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import { getHotBlogs, getBlog, likeBlog } from '@/api/blog'
import { getShopTypes } from '@/api/shop'
import BlogCard from '@/components/content/BlogCard.vue'
import PageState from '@/components/common/PageState.vue'
import type { Blog, ShopType } from '@/types/api'
type ViewState = 'loading' | 'error' | 'empty' | 'ready'
const router = useRouter(); const types = ref<ShopType[]>([]); const blogs = ref<Blog[]>([]); const typeState = ref<ViewState>('loading'); const blogState = ref<ViewState>('loading'); const typeError = ref(''); const blogError = ref(''); const paginationError = ref(''); const page = ref(1); const loadingMore = ref(false); const exhausted = ref(false); const loadMoreTrigger = ref<HTMLElement>(); let observer: IntersectionObserver | undefined
async function loadTypes() { typeState.value = 'loading'; typeError.value = ''; try { types.value = await getShopTypes(); typeState.value = types.value.length ? 'ready' : 'empty' } catch { typeError.value = '分类加载失败，请稍后重试。'; typeState.value = 'error' } }
async function loadBlogs(reset = false) { if (loadingMore.value || (!reset && exhausted.value)) return; loadingMore.value = true; paginationError.value = ''; if (reset) { page.value = 1; exhausted.value = false; blogs.value = []; blogState.value = 'loading' } try { const next = await getHotBlogs(page.value); if (!next.length) { exhausted.value = true; blogState.value = blogs.value.length ? 'ready' : 'empty'; return } const ids = new Set(blogs.value.map((blog) => blog.id)); blogs.value.push(...next.filter((blog) => !ids.has(blog.id))); page.value += 1; blogState.value = 'ready' } catch { blogError.value = '热门博客加载失败，请稍后重试。'; if (blogs.value.length) { paginationError.value = blogError.value; blogState.value = 'ready' } else { blogState.value = 'error' } } finally { loadingMore.value = false } }
function reloadBlogs() { return loadBlogs(true) }
function retryPage() { return loadBlogs() }
function goType(type: ShopType) { router.push({ name: 'shops', query: { type: type.id, name: type.name || '' } }) }
function goBlog(blog: Blog) { if (blog.id !== undefined) router.push({ name: 'blog-detail', params: { id: blog.id } }) }
async function handleLike(blog: Blog) { if (blog.id === undefined) return; try { await likeBlog(blog.id); const refreshed = await getBlog(blog.id); const index = blogs.value.findIndex((item) => item.id === blog.id); if (index >= 0) blogs.value[index] = refreshed } catch { ElMessage.error('点赞未成功，请稍后重试') } }
onMounted(() => { void loadTypes(); void loadBlogs(true); if ('IntersectionObserver' in window && loadMoreTrigger.value) { observer = new IntersectionObserver((entries) => { if (entries.some((entry) => entry.isIntersecting)) void loadBlogs() }, { rootMargin: '160px' }); observer.observe(loadMoreTrigger.value) } })
onBeforeUnmount(() => observer?.disconnect())
</script>

<style scoped>
.home-view{max-width:960px;margin:0 auto}.home-hero{padding:clamp(22px,5vw,52px);border-radius:var(--radius-card);background:linear-gradient(125deg,#ffdcc9,#fff6ef 65%,#ffe8bc)}.home-hero p{margin:0;color:#914d29;font-size:.9rem;font-weight:700}.home-hero h1{max-width:11ch;margin:10px 0 24px;font-size:clamp(2rem,5vw,3.7rem);line-height:1.1;letter-spacing:-.05em}.search-entry{display:flex;align-items:center;gap:8px;width:min(100%,420px);min-height:48px;padding:10px 15px;border:1px solid #edbca2;border-radius:var(--radius-control);background:#fff;color:var(--color-muted);font:inherit;text-align:left;cursor:not-allowed}.search-entry svg{width:20px;color:var(--color-primary)}.type-section,.hot-section{margin-top:34px}.type-section h2,.hot-section h2{margin:0;font-size:1.32rem}.type-list{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:16px}.type-item{display:grid;justify-items:center;gap:7px;min-height:96px;padding:12px 4px;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface);color:var(--color-ink);font:inherit;cursor:pointer}.type-item:hover{border-color:var(--color-primary);color:var(--color-primary)}.type-item img,.type-icon{display:grid;place-items:center;width:36px;height:36px;object-fit:contain;color:var(--color-primary)}.type-icon svg{width:100%;height:100%}.type-item span:last-child{max-width:100%;overflow:hidden;font-size:.82rem;white-space:nowrap;text-overflow:ellipsis}.section-heading{display:flex;align-items:baseline;justify-content:space-between;margin-bottom:16px}.section-heading span{color:var(--color-muted);font-size:.85rem}.blog-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.load-more{min-height:20px;padding:16px 0;color:var(--color-muted);font-size:.85rem;text-align:center}@media(min-width:768px){.type-list{grid-template-columns:repeat(6,1fr)}.blog-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}}@media(min-width:1200px){.blog-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
</style>
