<template>
  <section class="profile-header"><img v-if="user.icon" class="profile-header__avatar" :src="user.icon" :alt="`${user.nickName || '用户'}的头像`" width="76" height="76" loading="lazy"><span v-else class="profile-header__avatar profile-header__avatar--fallback" role="img" :aria-label="`${user.nickName || '用户'}的头像`">{{ (user.nickName || '探').slice(0, 1) }}</span><div class="profile-header__body"><h1>{{ user.nickName || '未命名用户' }}</h1><p>{{ info.city || '城市信息待补充' }}</p><p class="profile-header__intro">{{ info.introduce || (ownProfile ? '添加个人简介，让大家更好地认识你。' : '这个人很懒，什么都没有留下。') }}</p><dl><div><dt>粉丝</dt><dd>{{ info.fans || 0 }}</dd></div><div><dt>关注</dt><dd>{{ info.followee || 0 }}</dd></div></dl></div><div v-if="ownProfile || showFollow" class="profile-header__actions"><template v-if="ownProfile"><button type="button" data-test="edit-profile" @click="$emit('edit')">编辑资料</button><button type="button" data-test="logout" class="profile-header__logout" @click="$emit('logout')">退出登录</button></template><button v-else type="button" data-test="toggle-follow" :aria-pressed="followed" :disabled="busy" @click="$emit('toggle-follow')">{{ busy ? '处理中…' : followed ? '已关注' : '关注' }}</button></div></section>
</template>

<script setup lang="ts">
import type { User, UserInfo } from '@/types/api'
withDefaults(defineProps<{ user: User; info: UserInfo; ownProfile: boolean; followed: boolean; busy: boolean; showFollow?: boolean }>(), { showFollow: true })
defineEmits<{ edit: []; logout: []; 'toggle-follow': [] }>()
</script>

<style scoped>
.profile-header{display:grid;grid-template-columns:76px minmax(0,1fr);gap:14px;padding:18px;border:1px solid var(--color-border);border-radius:var(--radius-card);background:var(--color-surface);box-shadow:var(--shadow-card)}.profile-header__avatar{width:76px;height:76px;border-radius:50%;object-fit:cover}.profile-header__avatar--fallback{display:grid;place-items:center;background:#f7c8af;color:#884625;font-size:1.6rem;font-weight:800}.profile-header__body{min-width:0}.profile-header__body h1,.profile-header__body p{margin:0}.profile-header__body h1{overflow:hidden;font-size:1.3rem;white-space:nowrap;text-overflow:ellipsis}.profile-header__body>p:not(.profile-header__intro){margin-top:2px;color:var(--color-muted);font-size:.84rem}.profile-header__intro{display:-webkit-box;margin-top:8px!important;overflow:hidden;color:var(--color-ink);font-size:.88rem;-webkit-box-orient:vertical;-webkit-line-clamp:2}.profile-header dl{display:flex;gap:16px;margin:10px 0 0}.profile-header dl div{display:flex;gap:4px}.profile-header dt,.profile-header dd{margin:0;font-size:.8rem}.profile-header dt{color:var(--color-muted)}.profile-header dd{font-weight:700}.profile-header__actions{grid-column:1/-1;display:flex;gap:8px}.profile-header__actions button{min-height:44px;padding:8px 13px;border:1px solid var(--color-primary);border-radius:var(--radius-control);background:#fff0ea;color:var(--color-primary);font:inherit;font-weight:700;cursor:pointer}.profile-header__actions button:disabled{cursor:wait;opacity:.65}.profile-header__logout{border-color:var(--color-border)!important;background:#fff!important;color:var(--color-muted)!important}@media(min-width:560px){.profile-header{grid-template-columns:76px minmax(0,1fr) auto}.profile-header__actions{grid-column:auto;align-self:start;justify-content:flex-end;flex-wrap:wrap}}
</style>
