server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #    default-property-inclusion: non_null # JSON处理时忽略非空字段
  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
app:
  upload:
    directory: ${UPLOAD_DIR:./uploads}
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.dianping: debug

security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl: PT15M
    refresh-ttl: P7D
