<template>
  <section class="profile-view"><PageState v-if="state !== 'ready'" :state="state" :message="errorMessage" @retry="load"/><template v-else-if="user"><ProfileHeader :user="user" :info="info" :own-profile="true" :followed="false" :busy="loggingOut" @edit="router.push({ name: 'edit-profile' })" @logout="requestLogout"/><div class="profile-tabs" role="tablist" aria-label="我的内容"><button type="button" role="tab" :aria-selected="activeTab === 'notes'" @click="activeTab = 'notes'">我的笔记</button><button type="button" role="tab" :aria-selected="activeTab === 'feed'" @click="showFeed">关注动态</button></div><section v-if="activeTab === 'notes'" class="profile-content"><PageState v-if="!blogs.length && blogError" state="error" :message="blogError" @retry="loadBlogs"/><PageState v-else-if="!blogs.length" state="empty"/><div v-else class="blog-grid"><BlogCard v-for="blog in blogs" :key="blog.id" :blog="blog" @open="openBlog" @like="openBlog"/></div></section><section v-else class="profile-content feed-list" @scroll.passive="onFeedScroll"><PageState v-if="!feedBlogs.length && feedState !== 'ready'" :state="feedState" :message="feedError" @retry="() => loadFeed(true)"/><div v-else class="blog-grid"><BlogCard v-for="blog in feedBlogs" :key="blog.id" :blog="blog" @open="openBlog" @like="openBlog"/></div><PageState v-if="feedError && feedBlogs.length" state="error" :message="feedError" @retry="() => loadFeed()"/><p v-else-if="feedLoading" class="feed-status">正在加载关注动态…</p><p v-else-if="feedExhausted" class="feed-status">已经到底啦</p></section></template></section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { getUserInfo } from '@/api/user'
import { getFollowFeed, getMyBlogs } from '@/api/blog'
import { useAuthStore } from '@/stores/auth'
import ProfileHeader from '@/components/profile/ProfileHeader.vue'
import BlogCard from '@/components/content/BlogCard.vue'
import PageState from '@/components/common/PageState.vue'
import type { Blog, User, UserInfo } from '@/types/api'
type ViewState = 'loading' | 'error' | 'empty' | 'ready'
const router = useRouter(); const auth = useAuthStore(); const user = ref<User>(); const info = ref<UserInfo>({}); const blogs = ref<Blog[]>([]); const state = ref<ViewState>('loading'); const errorMessage = ref(''); const blogError = ref(''); const activeTab = ref<'notes' | 'feed'>('notes'); const feedBlogs = ref<Blog[]>([]); const feedState = ref<ViewState>('empty'); const feedError = ref(''); const feedLoading = ref(false); const feedExhausted = ref(false); const feedLastId = ref(Date.now() + 1); const feedOffset = ref(0); const loggingOut = ref(false)
async function loadBlogs() { blogError.value = ''; try { blogs.value = await getMyBlogs(1) } catch { blogError.value = '我的笔记加载失败，请稍后重试。' } }
async function load() { state.value = 'loading'; errorMessage.value = ''; try { const current = await auth.fetchCurrentUser(); if (current.id === undefined) throw new Error('缺少用户标识'); user.value = current; const [detail] = await Promise.all([getUserInfo(current.id), loadBlogs()]); info.value = detail || {}; state.value = 'ready' } catch { state.value = 'error'; errorMessage.value = '个人主页加载失败，请稍后重试。' } }
async function loadFeed(reset = false) { if (feedLoading.value || (!reset && feedExhausted.value)) return; if (reset) { feedBlogs.value = []; feedLastId.value = Date.now() + 1; feedOffset.value = 0; feedExhausted.value = false; feedState.value = 'loading' } feedLoading.value = true; feedError.value = ''; try { const result = await getFollowFeed(feedLastId.value, feedOffset.value); const next = result?.list || []; const known = new Set(feedBlogs.value.map((item) => item.id)); feedBlogs.value.push(...next.filter((item) => !known.has(item.id))); feedLastId.value = result?.minTime ?? feedLastId.value; feedOffset.value = result?.offset ?? 0; feedExhausted.value = !next.length; feedState.value = feedBlogs.value.length ? 'ready' : 'empty' } catch { feedError.value = '关注动态加载失败，请稍后重试。'; feedState.value = feedBlogs.value.length ? 'ready' : 'error' } finally { feedLoading.value = false } }
function showFeed() { activeTab.value = 'feed'; if (feedState.value === 'empty' && !feedBlogs.value.length && !feedExhausted.value) void loadFeed(true) } function onFeedScroll(event: Event) { const element = event.currentTarget as HTMLElement; if (element.scrollTop + element.clientHeight >= element.scrollHeight - 24) void loadFeed() } function openBlog(blog: Blog) { if (blog.id !== undefined) void router.push({ name: 'blog-detail', params: { id: blog.id } }) }
async function requestLogout() { if (!window.confirm('确认退出登录吗？')) return; loggingOut.value = true; try { await auth.signOut() } catch { /* auth store 的 finally 已负责清理；仍回到首页 */ } finally { await router.push({ name: 'home' }); loggingOut.value = false } }
void load()
</script>

<style scoped>
.profile-view{max-width:900px;margin:0 auto}.profile-tabs{display:flex;gap:8px;margin-top:20px;border-bottom:1px solid var(--color-border)}.profile-tabs button{min-height:44px;padding:8px 14px;border:0;border-bottom:3px solid transparent;background:transparent;color:var(--color-muted);font:inherit;font-weight:700;cursor:pointer}.profile-tabs button[aria-selected="true"]{border-bottom-color:var(--color-primary);color:var(--color-primary)}.profile-content{margin-top:16px}.blog-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.feed-list{max-height:62vh;overflow:auto}.feed-status{color:var(--color-muted);font-size:.85rem;text-align:center}@media(min-width:768px){.blog-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}}
</style>
