<template>
  <section class="profile-view"><PageState v-if="state !== 'ready'" :state="state" :message="errorMessage" @retry="load"/><template v-else-if="user"><ProfileHeader :user="user" :info="info" :own-profile="false" :show-follow="canFollow" :followed="followed" :busy="followBusy" @toggle-follow="toggleFollow"/><div class="profile-tabs" role="tablist" aria-label="用户内容"><button type="button" role="tab" :aria-selected="activeTab === 'notes'" @click="showNotes">笔记</button><button type="button" role="tab" :aria-selected="activeTab === 'common'" @click="showCommon">共同关注</button></div><section v-if="activeTab === 'notes'" class="profile-content"><PageState v-if="!blogs.length && blogError" state="error" :message="blogError" @retry="loadBlogs"/><PageState v-else-if="!blogs.length" state="empty"/><div v-else class="blog-grid"><BlogCard v-for="blog in blogs" :key="blog.id" :blog="blog" @open="openBlog" @like="openBlog"/></div></section><section v-else class="profile-content"><PageState v-if="commonState !== 'ready'" :state="commonState" :message="commonError" @retry="loadCommon"/><div v-else class="common-list"><button v-for="person in common" :key="person.id" type="button" @click="openUser(person.id)"><img v-if="person.icon" :src="person.icon" :alt="`${person.nickName || '用户'}的头像`" width="44" height="44" loading="lazy"><span v-else class="common-avatar" aria-hidden="true">{{ (person.nickName || '探').slice(0, 1) }}</span><span>{{ person.nickName || '未命名用户' }}</span></button></div></section></template></section>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import { getUser, getUserInfo } from '@/api/user'
import { getBlogsByUser } from '@/api/blog'
import { getCommonFollows, getFollowStatus, setFollow } from '@/api/follow'
import { useAuthStore } from '@/stores/auth'
import ProfileHeader from '@/components/profile/ProfileHeader.vue'
import BlogCard from '@/components/content/BlogCard.vue'
import PageState from '@/components/common/PageState.vue'
import type { Blog, User, UserInfo } from '@/types/api'
type ViewState = 'loading' | 'error' | 'empty' | 'ready'
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const user = ref<User>(); const info = ref<UserInfo>({}); const blogs = ref<Blog[]>([]); const state = ref<ViewState>('loading'); const errorMessage = ref(''); const blogError = ref(''); const followed = ref(false); const followBusy = ref(false); const activeTab = ref<'notes' | 'common'>('notes'); const common = ref<User[]>([]); const commonState = ref<ViewState>('empty'); const commonError = ref(''); const identityKnown = ref(!auth.isAuthenticated || !!auth.user); let profileEpoch = 0; let blogsEpoch = 0; let commonEpoch = 0
const userId = () => Number(route.params.id); const canFollow = computed(() => !auth.isAuthenticated || identityKnown.value)
function resetForRoute() { user.value = undefined; info.value = {}; blogs.value = []; blogError.value = ''; followed.value = false; followBusy.value = false; activeTab.value = 'notes'; common.value = []; commonState.value = 'empty'; commonError.value = ''; blogsEpoch += 1; commonEpoch += 1; identityKnown.value = !auth.isAuthenticated || !!auth.user }
async function loadBlogs(id = userId()) { const routeEpoch = profileEpoch; const requestEpoch = ++blogsEpoch; blogError.value = ''; try { const next = await getBlogsByUser(id, 1); if (routeEpoch !== profileEpoch || requestEpoch !== blogsEpoch) return; blogs.value = next } catch { if (routeEpoch !== profileEpoch || requestEpoch !== blogsEpoch) return; blogError.value = '用户笔记加载失败，请稍后重试。' } }
async function load() { const routeEpoch = ++profileEpoch; resetForRoute(); const id = userId(); if (!Number.isInteger(id) || id < 1) { state.value = 'error'; errorMessage.value = '用户地址无效，请返回后重新选择。'; return } let identity = auth.user; if (auth.isAuthenticated && !identity) { identityKnown.value = false; try { identity = await auth.fetchCurrentUser(); if (routeEpoch !== profileEpoch) return; identityKnown.value = true } catch { if (routeEpoch !== profileEpoch) return; identityKnown.value = false } } if (identity?.id === id) { if (routeEpoch === profileEpoch) await router.replace({ name: 'me' }); return } state.value = 'loading'; errorMessage.value = ''; try { const loaded = await getUser(id); if (routeEpoch !== profileEpoch) return; if (!loaded) throw new Error('用户不存在'); user.value = loaded; const [detail, userBlogs, followStatus] = await Promise.all([getUserInfo(id), getBlogsByUser(id, 1), auth.isAuthenticated && identityKnown.value ? getFollowStatus(id) : Promise.resolve(false)]); if (routeEpoch !== profileEpoch) return; info.value = detail || {}; blogs.value = userBlogs; followed.value = followStatus; state.value = 'ready' } catch { if (routeEpoch !== profileEpoch) return; state.value = 'error'; errorMessage.value = '用户主页加载失败，请稍后重试。' } }
async function loadCommon() { const routeEpoch = profileEpoch; const requestEpoch = ++commonEpoch; const id = userId(); commonState.value = 'loading'; commonError.value = ''; try { const next = await getCommonFollows(id); if (routeEpoch !== profileEpoch || requestEpoch !== commonEpoch || activeTab.value !== 'common') return; common.value = next; commonState.value = common.value.length ? 'ready' : 'empty' } catch { if (routeEpoch !== profileEpoch || requestEpoch !== commonEpoch || activeTab.value !== 'common') return; commonState.value = 'error'; commonError.value = '共同关注加载失败，请稍后重试。' } }
function showNotes() { activeTab.value = 'notes'; commonEpoch += 1 } function showCommon() { activeTab.value = 'common'; if (commonState.value === 'empty' && !common.value.length) void loadCommon() } async function toggleFollow() { if (!auth.isAuthenticated) { await router.push({ name: 'login', query: { redirect: route.fullPath } }); return } if (!identityKnown.value) return; const id = userId(); const routeEpoch = profileEpoch; if (followBusy.value) return; followBusy.value = true; try { await setFollow(id, !followed.value); if (routeEpoch !== profileEpoch || id !== userId()) return; followed.value = !followed.value } catch { if (routeEpoch !== profileEpoch || id !== userId()) return; ElMessage.error('关注操作未成功，请稍后重试') } finally { if (routeEpoch === profileEpoch && id === userId()) followBusy.value = false } } function openBlog(blog: Blog) { if (blog.id !== undefined) void router.push({ name: 'blog-detail', params: { id: blog.id } }) } function openUser(id: number | undefined) { if (id !== undefined) void router.push({ name: 'user-profile', params: { id } }) }
void load(); watch(() => route.params.id, () => { void load() })
</script>

<style scoped>
.profile-view{max-width:900px;margin:0 auto}.profile-tabs{display:flex;gap:8px;margin-top:20px;border-bottom:1px solid var(--color-border)}.profile-tabs button{min-height:44px;padding:8px 14px;border:0;border-bottom:3px solid transparent;background:transparent;color:var(--color-muted);font:inherit;font-weight:700;cursor:pointer}.profile-tabs button[aria-selected="true"]{border-bottom-color:var(--color-primary);color:var(--color-primary)}.profile-content{margin-top:16px}.blog-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.common-list{display:grid;gap:10px}.common-list button{display:flex;align-items:center;gap:11px;width:100%;min-height:60px;padding:8px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:inherit;font:inherit;text-align:left;cursor:pointer}.common-list img,.common-avatar{width:44px;height:44px;border-radius:50%;object-fit:cover}.common-avatar{display:grid;place-items:center;background:#f7c8af;color:#884625;font-weight:700}@media(min-width:768px){.blog-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}}
</style>
